### ISSUE TITLE
Provide a build script (.anaconda.yml) to run on someone elses' repo

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/anaconda-build#139]
I don't want to fork other peoples repos.  I just want to tell Anaconda Build "setup a webhook on this repo here, and when there is a commit on this branch, run this build script".  I want to provide the build script, that's it.

Is this possible right now?  It sure would be useful.

**Comment by PeterDSteinberg** [comment]
@ijstokes  When I attempt to set up a webhook on a repository that I do not own, i get  an error in the anaconda repo UI saying: ```You must have push access to the repository```.  I'm not sure how to accomplish what this issue aims to do.  I haven't seen an example of one person using someone else's push event's data, but I'm not too well versed in this.  When I look at the push event data for my repo that has anaconda-build CI, there's a lot of detail in there that not every repository owner may want to push to unknown people.

**Comment by stephenakearns** [comment]
closing issue after waiting a few weeks - please reopen when time permit to provide more detail
