### ISSUE TITLE
create a testing queue with groups/permissions of build-binstar-continuum

### ISSUE THREAD

**Issue by PeterDSteinberg** [Anaconda-Platform/anaconda-build#267]
It would be nice to deploy workers to a testing queue, test them out with all the team members who have access to the internal `build-binstar-continuum`, then change the workers to the production `build-binstar-continuum` queue.  The new testing queue should have the same group access as the `build-binstar-continuum` queue.

**Comment by PeterDSteinberg** [comment]
Here is the new testing queue: `build-binstar-continuum_beta` .

The group membership [shown here](https://beta.anaconda.org/binstar/queues/continuum_beta/settings) is the same as the `build-binstar-continuum` queue.

**Comment by insertinterestingnamehere** [comment]
This is great! Thanks for taking care of that!
