### ISSUE TITLE
Provide File-level Caching so that build runs are faster

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/anaconda-build#271]
TravisCI lets you reuse files left-over from previous builds - e.g. have lots of PIP packages or tarballs. 

Parent issue - anaconda-server/anaconda-server#880

Additional Input from @bryevdv ... 

As for caching, what would be ideal is to tie particular install steps to particular files: want to be able to say "oh, packages.json is updated, need to run the npm install again and re-cache just that" I guess there's three parts that would make it the most configurable: `(thing to cache, thing to check timestamp of, code to update cached thing when needed)`

**Comment by damianavila** [comment]
:+1:  to this request... specifically Bryan suggestion because it is something that TravisCI (and probably other services) don't have...
