### ISSUE TITLE
Docs: better info on build matrix (to split by groups) 

### ISSUE THREAD

**Issue by stephenakearns** [Anaconda-Platform/anaconda-build#272]
related to anaconda-server/anaconda-server#880

**Comment by damianavila** [comment]
So, do we have groups functionality in Anaconda build? I guess it is trough the `env` tag in the 3rd dimension of the matrix... am I right?

**Comment by dsludwig** [comment]
@damianavila, that is correct. There are 3 build dimensions:
- platform
  - the operating system and architecture to execute on
- engine
  - the initial set of packages to install in the conda environment
- env
  - a list of environment variables to define

When a build is launched, a sub-build is created for each combination of these dimensions. For example, if you have the platforms `[linux-64, win-64, osx-64]`, the engines `[python=2.7, python=3.5]` and the envvars `[TESTONLY=1, TESTONLY=0]`, then `3 * 2 * 2 = 12` builds will be launched.

If you want to suppress one of these combinations, you can do so by appending this to the end of your build configuration:

```
---
platform: win-64
engine: python=2.7
exclude: true
```

You can also add a build that is separate from the matrix in the same way:

```
---
platform: linux-64
engine: python=2.7
script:
  - upload_docs.py
```

The documentation for this feature is [here](http://docs.anaconda.org/build.html#BuildMatrix)

**Comment by damianavila** [comment]
OK, thanks for the explanation @dsludwig
